---
- name: Install Docker
  become: true
  ansible.builtin.dnf:
    name: docker
    state: present

- name: Start and enable Docker
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add ec2-user to the Docker group
  become: true
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true